-- CreateTable
CREATE TABLE "AppSettings" (
    "id" TEXT NOT NULL,
    "userRegistration" BOOLEAN NOT NULL DEFAULT true,
    "maxUploadSize" INTEGER NOT NULL DEFAULT 500,
    "defaultVideoQuality" TEXT NOT NULL DEFAULT '720p',
    "defaultLanguage" TEXT NOT NULL DEFAULT 'en',
    "enableEmailNotifications" BOOLEAN NOT NULL DEFAULT true,
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "fromEmail" TEXT NOT NULL DEFAULT 'noreply@reelscreator.com',
    "smtpHost" TEXT,
    "smtpPort" TEXT,
    "smtpUsername" TEXT,
    "smtpPassword" TEXT,
    "enableSMTP" BOOLEAN NOT NULL DEFAULT false,
    "trialPeriod" INTEGER NOT NULL DEFAULT 14,
    "defaultPlan" TEXT NOT NULL DEFAULT 'basic',
    "enableRecurring" BOOLEAN NOT NULL DEFAULT true,
    "gracePeriod" INTEGER NOT NULL DEFAULT 3,
    "allowCancellation" BOOLEAN NOT NULL DEFAULT true,
    "stripePublishableKey" TEXT,
    "stripeSecretKey" TEXT,
    "stripeWebhookSecret" TEXT,
    "stripeLiveMode" BOOLEAN NOT NULL DEFAULT false,
    "privacyPolicy" TEXT,
    "termsOfService" TEXT,
    "cookiePolicy" TEXT,
    "dataRetentionDays" INTEGER NOT NULL DEFAULT 90,
    "allowDataExport" BOOLEAN NOT NULL DEFAULT true,
    "storageProvider" TEXT NOT NULL DEFAULT 'local',
    "s3BucketName" TEXT,
    "s3AccessKey" TEXT,
    "s3SecretKey" TEXT,
    "s3Region" TEXT,
    "maxStorageGB" INTEGER NOT NULL DEFAULT 50,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AppSettings_pkey" PRIMARY KEY ("id")
); 